import { hashSync } from 'bcryptjs';

export const categories: string[] = [
  'Shirts',
  'Pants',
  'Shoes',
  'Accessories',
  'Outerwear',
  'Activewear',
  'Formalwear',
  'Casualwear',
  'Swimwear',
  'Underwear',
];

export interface IProductSeedInput {
  name: string;
  slug: string;
  description: string;
  gender: 'men' | 'women' | 'kid' | 'unisex';
  stock: number;
  sizes: ValidSizes[];
  price: number;
  rating: number;
  numReviews: number;
  isFeatured: boolean;
  banner: string | null;
  category: string;
  images: string[];
}

type ValidSizes = 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL';

export interface IUserSeedInput {
  name: string;
  email: string;
  password: string;
  role: 'admin' | 'user';
}

export const users: IUserSeedInput[] = [
  {
    name: 'John Doe',
    email: 'test@gmail.com',
    password: hashSync('123456', 10),
    role: 'admin',
  },
  {
    name: 'Jane Smith',
    email: 'test1@gmail.com',
    password: hashSync('123456', 10),
    role: 'user',
  },
];

export const products: IProductSeedInput[] = [
  {
    name: 'Polo Sporting Stretch Shirt',
    slug: 'polo-sporting-stretch-shirt',
    description: 'Classic Polo style with modern comfort',
    gender: 'men',
    stock: 5,
    sizes: ['S', 'M', 'L', 'XL'],
    price: 59.99,
    rating: 4.5,
    numReviews: 10,
    isFeatured: true,
    banner: 'banner-1.jpg',
    category: 'Shirts',
    images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
  },
  {
    name: 'Brooks Brothers Long Sleeved Shirt',
    slug: 'brooks-brothers-long-sleeved-shirt',
    description: 'Timeless style and premium comfort',
    gender: 'men',
    stock: 10,
    sizes: ['M', 'L', 'XL'],
    price: 85.9,
    rating: 4.2,
    numReviews: 8,
    isFeatured: true,
    banner: 'banner-2.jpg',
    category: 'Shirts',
    images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
  },
  {
    name: 'Tommy Hilfiger Classic Fit Dress Shirt',
    slug: 'tommy-hilfiger-classic-fit-dress-shirt',
    description: 'A perfect blend of sophistication and comfort',
    gender: 'men',
    stock: 0,
    sizes: ['M', 'L'],
    price: 99.95,
    rating: 4.9,
    numReviews: 3,
    isFeatured: false,
    banner: null,
    category: 'Shirts',
    images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
  },
  {
    name: 'Calvin Klein Slim Fit Stretch Shirt',
    slug: 'calvin-klein-slim-fit-stretch-shirt',
    description: 'Streamlined design with flexible stretch fabric',
    gender: 'men',
    stock: 10,
    sizes: ['S', 'M', 'L'],
    price: 39.95,
    rating: 3.6,
    numReviews: 5,
    isFeatured: false,
    banner: null,
    category: 'Shirts',
    images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
  },
  {
    name: 'Polo Ralph Lauren Oxford Shirt',
    slug: 'polo-ralph-lauren-oxford-shirt',
    description: 'Iconic Polo design with refined oxford fabric',
    gender: 'men',
    stock: 6,
    sizes: ['M', 'L', 'XL'],
    price: 79.99,
    rating: 4.7,
    numReviews: 18,
    isFeatured: false,
    banner: null,
    category: 'Shirts',
    images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
  },
  {
    name: 'Polo Classic Pink Hoodie',
    slug: 'polo-classic-pink-hoodie',
    description: 'Soft, stylish, and perfect for laid-back days',
    gender: 'men',
    stock: 8,
    sizes: ['M', 'L', 'XL'],
    price: 99.99,
    rating: 4.6,
    numReviews: 12,
    isFeatured: true,
    banner: null,
    category: 'Shirts',
    images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
  },
  {
    name: 'Levi Strauss Original Fit Jeans',
    slug: 'levi-strauss-original-fit-jeans',
    description: 'The ultimate classic straight leg jeans',
    gender: 'men',
    stock: 25,
    sizes: ['M', 'L', 'XL', 'XXL'],
    price: 69.50,
    rating: 4.8,
    numReviews: 145,
    isFeatured: true,
    banner: null,
    category: 'Pants',
    images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
  },
  {
    name: 'Nike Air Max 270 Sneakers',
    slug: 'nike-air-max-270-sneakers',
    description: 'Lightweight, breathable athletic shoes with max cushioning',
    gender: 'unisex',
    stock: 12,
    sizes: ['S', 'M', 'L'],
    price: 150.00,
    rating: 4.9,
    numReviews: 320,
    isFeatured: true,
    banner: 'banner-1.jpg',
    category: 'Shoes',
    images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
  },
  {
    name: 'Adidas Ultraboost Light',
    slug: 'adidas-ultraboost-light',
    description: 'High-performance running shoes with responsive energy return',
    gender: 'women',
    stock: 0,
    sizes: ['S', 'M'],
    price: 190.00,
    rating: 4.7,
    numReviews: 89,
    isFeatured: false,
    banner: null,
    category: 'Shoes',
    images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
  },
  {
    name: 'North Face Resolve 2 Jacket',
    slug: 'north-face-resolve-2-jacket',
    description: 'Waterproof, breathable jacket for all-weather adventures',
    gender: 'women',
    stock: 15,
    sizes: ['XS', 'S', 'M', 'L'],
    price: 89.00,
    rating: 4.5,
    numReviews: 45,
    isFeatured: true,
    banner: null,
    category: 'Outerwear',
    images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
  },
  {
    name: 'Columbia Steens Mountain Fleece',
    slug: 'columbia-steens-mountain-fleece',
    description: 'Cozy and durable full-zip fleece jacket',
    gender: 'men',
    stock: 40,
    sizes: ['M', 'L', 'XL', 'XXL'],
    price: 45.00,
    rating: 4.6,
    numReviews: 210,
    isFeatured: false,
    banner: null,
    category: 'Outerwear',
    images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
  },
  {
    name: 'Lululemon Align High-Rise Pant',
    slug: 'lululemon-align-high-rise-pant',
    description: 'Weightless, buttery soft yoga pants',
    gender: 'women',
    stock: 30,
    sizes: ['XS', 'S', 'M'],
    price: 98.00,
    rating: 4.9,
    numReviews: 500,
    isFeatured: true,
    banner: 'banner-2.jpg',
    category: 'Activewear',
    images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
  },
  {
    name: 'Under Armour Tech 2.0 T-Shirt',
    slug: 'under-armour-tech-2-0-t-shirt',
    description: 'Quick-drying, ultra-soft athletic tee',
    gender: 'men',
    stock: 50,
    sizes: ['S', 'M', 'L', 'XL'],
    price: 25.00,
    rating: 4.4,
    numReviews: 312,
    isFeatured: false,
    banner: null,
    category: 'Activewear',
    images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
  },
  {
    name: 'Ray-Ban Classic Aviator Sunglasses',
    slug: 'ray-ban-classic-aviator-sunglasses',
    description: 'Timeless tear-drop style with premium UV protection',
    gender: 'unisex',
    stock: 18,
    sizes: ['M'],
    price: 161.00,
    rating: 4.8,
    numReviews: 125,
    isFeatured: true,
    banner: null,
    category: 'Accessories',
    images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
  },
  {
    name: 'Casio G-Shock Digital Watch',
    slug: 'casio-g-shock-digital-watch',
    description: 'Rugged, water-resistant digital sports watch',
    gender: 'men',
    stock: 22,
    sizes: ['M'],
    price: 55.00,
    rating: 4.7,
    numReviews: 890,
    isFeatured: false,
    banner: null,
    category: 'Accessories',
    images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
  },
  {
    name: 'Speedo Endurance+ Swimsuit',
    slug: 'speedo-endurance-swimsuit',
    description: 'Chlorine-resistant competitive swimsuit',
    gender: 'women',
    stock: 14,
    sizes: ['XS', 'S', 'M', 'L'],
    price: 49.50,
    rating: 4.3,
    numReviews: 67,
    isFeatured: false,
    banner: null,
    category: 'Swimwear',
    images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
  },
  {
    name: 'Calvin Klein Cotton Stretch Boxer Briefs',
    slug: 'calvin-klein-cotton-stretch-boxer-briefs',
    description: 'Pack of 3 breathable cotton boxers',
    gender: 'men',
    stock: 100,
    sizes: ['S', 'M', 'L', 'XL'],
    price: 42.50,
    rating: 4.8,
    numReviews: 1200,
    isFeatured: true,
    banner: null,
    category: 'Underwear',
    images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
  },
  {
    name: 'Kids GAP Logo T-Shirt',
    slug: 'kids-gap-logo-t-shirt',
    description: 'Classic comfortable cotton tee for kids',
    gender: 'kid',
    stock: 35,
    sizes: ['XS', 'S', 'M'],
    price: 15.00,
    rating: 4.6,
    numReviews: 45,
    isFeatured: false,
    banner: null,
    category: 'Shirts',
    images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
  },
  {
    name: 'Hugo Boss Slim Fit Suit',
    slug: 'hugo-boss-slim-fit-suit',
    description: 'Elegant two-piece wool blend formal suit',
    gender: 'men',
    stock: 4,
    sizes: ['M', 'L', 'XL'],
    price: 595.00,
    rating: 4.9,
    numReviews: 24,
    isFeatured: true,
    banner: 'banner-1.jpg',
    category: 'Formalwear',
    images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
  }
];
